name: Build-Tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@v0.3.9
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TAG_NAME: ${{ github.ref }}
          LATEST: "true"

      # - name: Docker Build & Push to GitHub Package
      #   uses: opspresso/action-docker@v0.3.9
      #   with:
      #     args: --docker
      #   env:
      #     PASSWORD: ${{ secrets.GHP_TOKEN }}
      #     REGISTRY: "docker.pkg.github.com"
      #     TAG_NAME: ${{ github.ref }}
